import { describe, expect, test } from 'vitest'
import { analyze } from '../index.js'

test('recognizes a font-family', () => {
  const fixture = `
    test {
      font-family: "Droid Sans", serif;
      font-family: sans-serif;
      font-family: "Arial Black", 'Arial Bold', Gadget, sans-serif;
      font-family: Brush Script MT, cursive;
      font-family: monospace;
      font-family: Consolas, "Liberation Mono", Menlo, Courier, monospace;
      font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol";

      /* Unrelated */
      color: brown;
      font-size: 12px;
    }
  `
  const actual = analyze(fixture).values.fontFamilies
  expect(actual.total).toBe(7)
  expect(actual.total_unique).toBe(7)
  expect(Array.from(actual.list())).toEqual([
    { name: '"Droid Sans", serif', count: 1 },
    { name: 'sans-serif', count: 1 },
    { name: `"Arial Black", 'Arial Bold', Gadget, sans-serif`, count: 1 },
    { name: 'Brush Script MT, cursive', count: 1 },
    { name: 'monospace', count: 1 },
    { name: 'Consolas, "Liberation Mono", Menlo, Courier, monospace', count: 1 },
    { name: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol"', count: 1 },
  ])
})

test('extracts the `font` shorthand', () => {
  const fixture = `
    test {
      font: large 'Noto Sans';
      font: normal normal 1em/1 "Source Sans Pro", serif;
      font: normal normal 1.2em serif;
      font: 400 1.3em/1 serif;
      font: 1em / 1 serif;
      font: 1em/ 1 serif;
      font: 1em /1 serif;
      font: normal normal 11px/1.5 -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol";
      font: 11px Consolas, "Liberation Mono", Menlo, Courier, monospace;
      font: 0/0 a; /* As generated by some css minifiers */
      font: 1.2em/1.2em; /* Found in indiatimes.com */
      font: 12px var(--fontStack-monospace, ui-monospace, SFMono-Regular, SF Mono, Menlo, Consolas, Liberation Mono, monospace); /* From github.com */

      /* Unrelated */
      color: brown;
      font-size: 123456789px;
    }
  `
  const actual = analyze(fixture).values.fontFamilies
  expect(actual.total).toBe(12)
  expect(actual.total_unique).toBe(8)
  expect(Array.from(actual.list())).toEqual([
    { name: `'Noto Sans'`, count: 1 },
    { name: `"Source Sans Pro", serif`, count: 1 },
    { name: 'serif', count: 5 },
    { name: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol"', count: 1 },
    { name: 'Consolas, "Liberation Mono", Menlo, Courier, monospace', count: 1 },
    { name: 'a', count: 1 },
    { name: 'var(--fontStack-monospace, ui-monospace, SFMono-Regular, SF Mono, Menlo, Consolas, Liberation Mono, monospace)', count: 1 },
    // This entry exists due to a ??bug?? in CSSTree, but it's better than not counting the value above this as well
    { name: 'ui-monospace, SFMono-Regular, SF Mono, Menlo, Consolas, Liberation Mono, monospace', count: 1 },
  ])
})

test('does not crash on `12px var(...)', () => {
  const fixture = `
    test {
      font: 12px var(--fontStack-monospace, ui-monospace, SFMono-Regular, SF Mono, Menlo, Consolas, Liberation Mono, monospace);
    }
  `
  expect(() => {
    analyze(fixture).values.fontFamilies
  }).not.toThrow()
})

test('handles system fonts', () => {
  // Source: https://drafts.csswg.org/css-fonts-3/#font-prop
  const fixture = `
    test {
      font: menu;        /* use the font settings for system menus */
      font: large menu;  /* use a font family named "menu" */
    }
  `
  const actual = analyze(fixture).values.fontFamilies
  expect(actual.total).toBe(1)
  expect(actual.total_unique).toBe(1)
  expect(Array.from(actual.list())).toEqual([
    { name: 'menu', count: 1 },
  ])
})

test('ignores keywords and global values', () => {
  const fixture = `
    test {
      /* Global values */
      font-family: inherit;
      font-family: initial;
      font-family: revert;
      font-family: revert-layer;
      font-family: unset;

      font: inherit;
      font: initial;
      font: revert;
      font: revert-layer;
      font: unset;
    }
  `
  const actual = analyze(fixture).values.fontFamilies
  expect(actual.total).toBe(0)
  expect(actual.total_unique).toBe(0)
})