import { test } from 'vitest'
import { expect } from 'vitest'
import { analyze } from '../index.js'

test('recognizes a font-size', () => {
	const fixture = `
    test {
      font-size: 10px;
      font-size: small;
      font-size: 1em;
      font-size: calc(3vw + 1em);

      /* Unrelated */
      color: brown;
      font-family: serif;
    }
  `
	const actual = analyze(fixture).values.fontSizes
	const expected = {
		total: 4,
		totalUnique: 4,
		unique: {
			'10px': 1,
			small: 1,
			'1em': 1,
			'calc(3vw + 1em)': 1,
		},
		uniquenessRatio: 4 / 4,
	}

	expect(actual).toEqual(expected)
})

test('extracts the `font` shorthand', () => {
	const fixture = `
    test {
      font: large "Noto Sans";
      font: normal normal 1em/1 "Source Sans Pro", serif;
      font: normal normal 1.2em serif;
      font: 400 1.3em/1 serif;
      font: 1em / 1 serif;
      font: 1em/ 1 serif;
      font: 1em /1 serif;
      font: 2em/1.4em serif;
      font: normal normal 11px/1.5 -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol";
      font: 11px Consolas, "Liberation Mono", Menlo, Courier, monospace;
      font: 0/0 a; /* As generated by some css minifiers */
      font: 10PX sans-serif;
      font: 12px var(--fontStack-monospace, ui-monospace, SFMono-Regular, SF Mono, Menlo, Consolas, Liberation Mono, monospace); /* from github.com */

      /* Unrelated */
      color: brown;
      font-family: serif;
    }
  `
	const actual = analyze(fixture).values.fontSizes
	const expected = {
		total: 13,
		totalUnique: 9,
		unique: {
			'0': 1,
			large: 1,
			'1em': 4,
			'1.2em': 1,
			'1.3em': 1,
			'2em': 1,
			'11px': 2,
			'10PX': 1,
			'12px': 1,
		},
		uniquenessRatio: 9 / 13,
	}
	expect(actual).toEqual(expected)
})

test('handles system fonts', () => {
	// Source: https://drafts.csswg.org/css-fonts-3/#font-prop
	const fixture = `
    test {
      font: menu;        /* use the font settings for system menus */
      font: large menu;  /* use a font family named "menu" */
    }
  `
	const actual = analyze(fixture).values.fontSizes
	const expected = {
		total: 1,
		totalUnique: 1,
		unique: {
			large: 1,
		},
		uniquenessRatio: 1,
	}

	expect(actual).toEqual(expected)
})

test('ignores keywords and global values', () => {
	const fixture = `
    test {
      /* Global values */
      font-size: inherit;
      font-size: initial;
      font-size: revert;
      font-size: revert-layer;
      font-size: unset;

      font: inherit;
      font: initial;
      font: revert;
      font: revert-layer;
      font: unset;
    }
  `
	const actual = analyze(fixture).values.fontSizes
	const expected = {
		total: 0,
		totalUnique: 0,
		unique: {},
		uniquenessRatio: 0,
	}

	expect(actual).toEqual(expected)
})
