import { describe, test } from 'vitest'
import { expect } from 'vitest'
import { analyze } from '../index.js'

test('recognizes line-height', () => {
	const fixture = `
    test {
      line-height: 1;
			line-height: 100%;
			line-height: calc(1em + 2vh);
			line-height: 2em;
			line-height: normal;
      /* Unrelated */
      color: brown;
      font-size: 12px;
    }
  `
	const actual = analyze(fixture).values.lineHeights
	const expected = {
		total: 5,
		totalUnique: 5,
		unique: {
			'1': 1,
			'100%': 1,
			'calc(1em + 2vh)': 1,
			'2em': 1,
			normal: 1,
		},
		uniquenessRatio: 5 / 5,
	}

	expect(actual).toEqual(expected)
})

test('extracts the `font` shorthand', () => {
	const fixture = `
    test {
      font: large 'Noto Sans';
      font: normal normal 1em/1 "Source Sans Pro", serif;
      font: normal normal 1.2em serif;
      font: 400 1.3em/1 serif;
      font: 1em / 1 serif;
      font: 1em/ 1 serif;
      font: 1em /1 serif;
      font: normal normal 11px/1.5 -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol";
      font: 11px Consolas, "Liberation Mono", Menlo, Courier, monospace;
      font: 0/0 a; /* As generated by some css minifiers */
      /* Unrelated */
      color: brown;
      font-size: 12px;
    }
  `
	const actual = analyze(fixture).values.lineHeights
	const expected = {
		total: 7,
		totalUnique: 3,
		unique: {
			'1': 5,
			'1.5': 1,
			'0': 1,
		},
		uniquenessRatio: 3 / 7,
	}
	expect(actual).toEqual(expected)
})

describe('normalizing', () => {
	test('line-height', () => {
		const actual = analyze(`test { line-height: 1EM }`).values.lineHeights.unique
		expect(actual).toEqual({ '1em': 1 })
	})

	test('font shorthand', () => {
		const actual = analyze(`test { font: 10PX/1EM serif }`).values.lineHeights.unique
		expect(actual).toEqual({ '1em': 1 })
	})

	test('leaves var() intact', () => {
		const actual = analyze(`test {
			line-height: var(--lineHeight1);
			line-height: VAR(--lineHeight2);
		}`).values.lineHeights.unique
		expect(actual).toEqual({
			'var(--lineHeight1)': 1,
			'VAR(--lineHeight2)': 1,
		})
	})
})

test('handles system fonts', () => {
	// Source: https://drafts.csswg.org/css-fonts-3/#font-prop
	const fixture = `
    test {
      font: menu;        /* use the font settings for system menus */
      font: large menu;  /* use a font family named "menu" */
    }
  `
	const actual = analyze(fixture).values.lineHeights
	const expected = {
		total: 0,
		totalUnique: 0,
		unique: {},
		uniquenessRatio: 0,
	}

	expect(actual).toEqual(expected)
})

test('ignores keywords and global values', () => {
	const fixture = `
		test {
			/* Global values */
			line-height: inherit;
			line-height: initial;
			line-height: revert;
			line-height: revert-layer;
			line-height: unset;

      font: inherit;
      font: initial;
      font: revert;
      font: revert-layer;
      font: unset;
		}
	`
	const actual = analyze(fixture).values.fontFamilies
	const expected = {
		total: 0,
		totalUnique: 0,
		unique: {},
		uniquenessRatio: 0,
	}

	expect(actual).toEqual(expected)
})
